nome_do_produto = input("Digite o nome do produto: ")
valor_do_produto = int(input('Digite o valor do produto:R$'))
valor_a_pagar = int(input('Digite o valor que você pagara pelo produto:R$'))
print('Seu troco será de: {} - {} = '.format(valor_a_pagar, valor_do_produto))
print(valor_a_pagar - valor_do_produto)
#Comprovante
print("---------------------------------")
print("      COMPROVANTE DE VENDA")
print("---------------------------------")
print(f"      Produto: {nome_do_produto}")
print(f"      Valor do produto: R${valor_do_produto}")
print(f"      Valor pago: R${valor_a_pagar}")
print(f"      Troco: R${valor_do_produto - valor_a_pagar}")
print("---------------------------------")
